let head = document.querySelector("header");
let nav = document.createElement("nav");
nav.className = "nav-bar";
let list = document.createElement("ul");
list.className = "nav-list";
let logo = document.createElement("h1");
logo.className = "logo";
logo.innerText = "HANESH";
let item1 = document.createElement("li");
item1.className = "item";
let item2 = document.createElement("li");
item2.className = "item";
let item3 = document.createElement("li");
item3.className = "item";
let item4 = document.createElement("li");
item4.className = "item";
let item5 = document.createElement("li");
item5.className = "item";
let home = document.createElement("a");
home.className = "link";
home.href = "index.html";
let about = document.createElement("a");
about.className = "link";
about.href = "about.html";
let prevwork = document.createElement("a");
prevwork.className = "link";
prevwork.href = "previouswork.html";
let project = document.createElement("a");
project.className = "link";
project.href = "projects.html";
let contact = document.createElement("a");
contact.className = "link";
contact.href = "contact.html";

let icon1 = document.createElement("i");
icon1.className = "fa-solid fa-house";
let icon2 = document.createElement("i");
icon2.className = "fa-solid fa-circle-info";
let icon3 = document.createElement("i");
icon3.className = "fa-solid fa-keyboard";
let icon4 = document.createElement("i");
icon4.className = "fa-solid fa-desktop";
let icon5 = document.createElement("i");
icon5.className = "fa-solid fa-address-card";

let span1 = document.createElement("span");
span1.className = "text1 ctext";
let span2 = document.createElement("span");
span2.className = "text2 ctext";
let span3 = document.createElement("span");
span3.className = "text3 ctext";
let span4 = document.createElement("span");
span4.className = "text4 ctext";
let span5 = document.createElement("span");
span5.className = "text5 ctext";

span1.innerText = "Home";
span2.innerText = "About";
span3.innerText = "PreviousWork";
span4.innerText = "Projects";
span5.innerText = "Contact";

let social = document.createElement("div");
social.className = "socialicons";
let gmail = document.createElement("i");
gmail.className = "fa-solid fa-envelope";
let git = document.createElement("i");
git.className = "fa-brands fa-github";
let linkdin = document.createElement("i");
linkdin.className = "fa-brands fa-linkedin";
let gmailicon = document.createElement("a");
gmailicon.href = "mailto:hanesh.koganti007@gmail.com";
gmailicon.ariaLabel = "first link";
let giticon = document.createElement("a");
giticon.href = "https://github.com/";
giticon.ariaLabel = "second link";
let linkicon = document.createElement("a");
linkicon.href = "https://www.linkedin.com/feed/";
linkicon.ariaLabel = "third link";

home.appendChild(icon1);
about.appendChild(icon2);
prevwork.appendChild(icon3);
project.appendChild(icon4);
contact.appendChild(icon5);
home.appendChild(span1);
about.appendChild(span2);
prevwork.appendChild(span3);
project.appendChild(span4);
contact.appendChild(span5);
item1.appendChild(home);
item2.appendChild(about);
item3.appendChild(prevwork);
item4.appendChild(project);
item5.appendChild(contact);
list.appendChild(item1);
list.appendChild(item2);
list.appendChild(item3);
list.appendChild(item4);
list.appendChild(item5);
social.append(gmail);
social.append(git);
social.append(linkdin);
nav.append(logo);
nav.appendChild(list);
nav.append(social);
head.appendChild(nav);
